### PR TITLE
Improved Design

### PR DESCRIPTION
**Pull request by Andy-404**
Screenshot_4
Screenshot_5

### CODE REVIEW

**Comment by Akash-Ramjyothi** [comment]
@Andy-404 Excellent work on the Background. However, I have few other concerns. The **Users Section** would be better if Opaque rather Translucent. Also I recommend to have different colors for the **Send button and Share location Button**. The **Source Code Button** is barely visible on the Login Page. Can you please provide a 1 minute demo video of the working of all functionalities here after making amends to the changes?

**Comment by Andy-404** [comment]
Sure will do that.

**Comment by Andy-404** [comment]
### Demo Video

https://user-images.githubusercontent.com/68277858/122668282-e595be00-d1d4-11eb-8460-15fd3ec3b03b.mp4

**Comment by Andy-404** [comment]
What improvements could be done @Akash-Ramjyothi ?

**Comment by Akash-Ramjyothi** [comment]
@Andy-404 Good job that you have made changes as requested. Can you please change the name on the Login Page which is **Display Name** and **Room** to bold style and Black color? Please do the above minor changes, and send a screenshot or a demo video, and I will merge it ASAP.

**Comment by Andy-404** [comment]
Screenshot_2
Is this fine @Akash-Ramjyothi ?

**Comment by Akash-Ramjyothi** [comment]
@Andy-404 Good work. Thank you for your contributions.

**Comment by Andy-404** [comment]
Glad you liked it!

**Pull request merged**
